version: 1
formatters:
  simple:
    format: '%(asctime)s - %(lineno)3s %(funcName)20s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: html2xlsx.log
    maxBytes: 1048576
    backupCount: 3
    encoding: utf8
loggers:
  werkzeug:
    level: DEBUG
    handlers: ['console', 'file']
    propagate: no
root:
  level: DEBUG
  handlers: ['console', 'file']